server:
  port: 9639

spring:
  application:
    name: Correspondence-App
  datasource:
   # driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@localhost:1521/xe
    #username: SYS as SYSDBA
    #password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tgh
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
    #database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        

  mail:
    
    host: smtp-mail.outlook.com
    port: 587
    username: akashk33@hotmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  
    
        
              
